/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.BookBUS;
import BUS.PhieuPhatBUS;
import BUS.PhieuTraBUS;
import DAO.BookDAO;

import DAO.PhieuTraDAO;
import DTO.Book;
import DTO.PhieuTra;
import JDBCConnection.JDBCConnection;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.CurrentUser;

/**
 *
 * @author VINH
 */
public class ThemPT extends javax.swing.JFrame {
    DefaultTableModel dtm;
     Connection conn;
     JDBCConnection cn = new JDBCConnection();
     PreparedStatement pst;
     ResultSet rs;
     QLTra qlt;
     PhieuTraBUS PhieuTraBUS;
     PhieuTra pt;
    /**
     * Creates new form ThemPT
     */
    public ThemPT(QLTra qlt) {
        initComponents();
        LoadMaDG();
        CurrentUser currentUser = CurrentUser.getInstance();
        String maND = currentUser.getMaND();
        txtMaTT.setText(maND);
        txtMaTT.setEditable(false);
        Text_HoTenDG.setEditable(false);
        pt = new PhieuTra();
        PhieuTraBUS = new PhieuTraBUS();
        this.qlt = qlt;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Date today = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String NgayTra = dateFormat.format(new java.sql.Date(today.getTime()));
        Text_NgayTra.setText(NgayTra);
        Text_NgayTra.setEditable(false);
        ComboBox_MaDG.addItemListener(new ItemListener() {
            public void itemStateChanged (ItemEvent ie) {
                if (ie.getStateChange() == ItemEvent.SELECTED) {
                    String MaDG = ComboBox_MaDG.getSelectedItem().toString();
                    String HoTenDG = getHoTenDG(MaDG);
                    Text_HoTenDG.setText(HoTenDG);
                    LoadSach(MaDG);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaTT = new javax.swing.JTextField();
        ComboBox_Sach = new javax.swing.JComboBox<>();
        btnThemSach = new javax.swing.JButton();
        Text_NgayTra = new javax.swing.JTextField();
        Text_HoTenDG = new javax.swing.JTextField();
        ComboBox_MaDG = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableDSSachMuon = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TẠO PHIẾU TRẢ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã độc giả :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên độc giả :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Người lập phiếu : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày trả :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Sách trả :");

        ComboBox_Sach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-book-16.png"))); // NOI18N
        btnThemSach.setText("Thêm");
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });

        Text_NgayTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_NgayTraActionPerformed(evt);
            }
        });

        ComboBox_MaDG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_MaDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_MaDGActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Danh sách sách trả :");

        tableDSSachMuon.setAutoCreateRowSorter(true);
        tableDSSachMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách"
            }
        ));
        jScrollPane6.setViewportView(tableDSSachMuon);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove (1).png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-24.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ok-24.png"))); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_MaDG, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_HoTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaTT, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(200, 200, 200)
                                    .addComponent(btnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ComboBox_Sach, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(102, 102, 102)))
                            .addComponent(Text_NgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBox_MaDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_HoTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_NgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboBox_Sach)
                    .addComponent(btnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnXoa)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean LoadMaDG() {
        conn = cn.getJDBCConnection();
        if (conn != null) {
                String sql = "SELECT MADOCGIA FROM DOCGIA " +
                             "WHERE MADOCGIA IN (" +
                                "SELECT MADOCGIA FROM PHIEUMUON PM " +
                                "JOIN CTPHIEUMUON CT ON PM.MAPHIEUMUON = CT.MAPHIEUMUON AND TRANGTHAI = 0" +
                                ")";
                try {
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
                    ComboBox_MaDG.removeAllItems();
                    ComboBox_MaDG.addItem("--Chọn độc giả--");
                    while (rs.next()) {
                        String maDG = rs.getString("MADOCGIA");
                        ComboBox_MaDG.addItem(maDG);
                    }
                    rs.close();
                    pst.close();
                }
             catch (SQLException e) {
                e.printStackTrace();
            }
            }
        return true;
    }
    
    private String getHoTenDG (String maDG) {
        String HoTenDG = "";
        try {
            String sql = "SELECT HOTEN FROM DOCGIA WHERE MADOCGIA = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,maDG);
            rs = pst.executeQuery();
            if (rs.next()) {
                HoTenDG = rs.getString("HOTEN");
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
        }
        return HoTenDG;
    }
    
    private boolean LoadSach(String maDG) {
        List<Book> books = new BookDAO().getBorrowedBooksByMaDG(maDG);
        ComboBox_Sach.removeAllItems();
        ComboBox_MaDG.addItem("--Chọn sách--");
        for (Book book : books) {
        ComboBox_Sach.addItem(book.getMaSach());
       
    }
         return true;
    }
    
    
    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        String maSach = ComboBox_Sach.getSelectedItem().toString();
        String maDG = ComboBox_MaDG.getSelectedItem().toString();
        Book bk = new BookBUS().getBookByMaSach(maSach);
        PhieuPhatBUS ppBUS = new PhieuPhatBUS();
        int songaytre = ppBUS.tinhSoNgayTraTre(maSach, maDG);
        DefaultTableModel dtm = (DefaultTableModel) tableDSSachMuon.getModel();
        if (songaytre > 0) {
                JOptionPane.showMessageDialog(null,"Sách đã hết hạn, vui lòng tạo phiếu phạt");
                return;
        }
        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (dtm.getValueAt(i,0).equals(bk.getMaSach())) {
                JOptionPane.showMessageDialog(null,"Sách đã tồn tại trong danh sách ");
                return;
            }  
        }
        dtm.addRow(new Object [] {bk.getMaSach(), bk.getTenSach()});
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selected = tableDSSachMuon.getSelectedRow();
        if (selected != -1) {
            DefaultTableModel dtm = (DefaultTableModel) tableDSSachMuon.getModel();
            dtm.removeRow(selected);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String noti = "";
        Date today = new Date();
        if (ComboBox_MaDG.getSelectedIndex() == 0) {
            noti += "Chưa chọn độc giả\n";
        }
        if (!noti.isEmpty()) {
            JOptionPane.showMessageDialog(null,noti);
        }
        else {
            int rowCount = tableDSSachMuon.getRowCount();
            String[] maSachArray = new String[rowCount];
            for (int i = 0; i < rowCount; i++) {
                maSachArray[i] = tableDSSachMuon.getValueAt(i, 0).toString();
            }
            pt.setMaTT(txtMaTT.getText());
            pt.setMaDG(ComboBox_MaDG.getSelectedItem().toString());
            pt.setNgayTra(new java.sql.Date(today.getTime()));
            PhieuTraDAO ptDAO = new PhieuTraDAO();
            ptDAO.addPhieuTra(pt, maSachArray);
            JOptionPane.showMessageDialog(null,"Thêm phiếu trả thành công");
            qlt.updateTable();
            this.dispose();
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void Text_NgayTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_NgayTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_NgayTraActionPerformed

    private void ComboBox_MaDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_MaDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_MaDGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ThemPT().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_MaDG;
    private javax.swing.JComboBox<String> ComboBox_Sach;
    private javax.swing.JTextField Text_HoTenDG;
    private javax.swing.JTextField Text_NgayTra;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tableDSSachMuon;
    private javax.swing.JTextField txtMaTT;
    // End of variables declaration//GEN-END:variables
}
